@startuml sms-enrollment
entity User
entity CoreService
entity Redis
entity Twilio

User <-> CoreService : User Logs In
User -> CoreService : Requests to enroll SMS MFA
CoreService -> Redis : Create Challenge Nonce for device
CoreService -> User : HTTP 412 PASSWORD Challenge Required
User -> CoreService : Sends Password
CoreService -> Redis : Confirm Challenge, create Success Nonce
CoreService -> User : Send Success Nonce Id and request SMS Enrollment
User -> CoreService : Provides Phone Number (FE with Nonce ID)
CoreService -> Redis : Create SMS Challenge Nonce
CoreService -> Twilio : Generate OTP Code and send to phone
CoreService -> User: Send Challenge Nonce to FE
Twilio ---> User : Send SMS
User -> CoreService : Send OTP Code and Challenge Noce ID
CoreService -> Redis : Confirm Challenge, consume nonce, save in DB
CoreService -> User : Send Success and Backup Code (first time only)

@enduml
