name: GitHub Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GCR_TOKEN }}
    - name: Build and Publish Image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/uptownhr/git-magic:latest
  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          script: |
            ls
            cd services/uptownhr
            git pull
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml --env-file prod.env up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.username }}
          key: ${{ secrets.PRIVATE_KEY }}
